version: "3.8"

services:
  db:
    image: postgres:15
    container_name: flowmind_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: flowmind_app
    restart: always
    depends_on:
      - db
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: >
      sh -c "alembic upgrade head &&
             uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload --log-level debug"

volumes:
  postgres_data:
